name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/app.yml
    permissions:
      contents: write
    with:
      release: true
